[global]
Name = Far_East_Mod
UIName = Far_East_Mod
Description = Far East War
DllName = LuaExtCore
ModVersion = 1.0
ModFolder = Far_East_Mod\Data
LocFolder = Far_East_Mod\Locale
ScenarioPackFolder = WW2\Scenarios
SpeechManagerCache = SpeechManagerCoH.cache

[game]
PlayerDropBehavior = aitakeover

[attrib:common]
folder = Far_East_Mod\DataAttrib
archive.01 = Far_East_Mod\Archives\FEMOD_Attrib
archive.02 = Far_East_Mod\Archives\FEMOD_Camera
archive.03 = Far_East_Mod\Archives\A_Sea_FE_2v2
archive.04 = WW2\Archives\AttribArchive

[preview:common]
folder = CoH\DataPreview

[movies:common]
folder = WW2\Movies

[movies:common:01]
folder = Engine\Movies

[data:common:01]
folder = Far_East_Mod\Data
archive.01 = Far_East_Mod\Archives\FEMOD_Data
archive.02 = Far_East_Mod\Archives\FEMOD_Maps
archive.03 = Far_East_Mod\Archives\FEMOD_DataModels

[data:common:02]
folder = WW2\Data
archive.01 = WW2\Archives\WW2Data
archive.02 = WW2\Archives\WW2Art
archive.03 = WW2\Archives\WW2Sound
archive.04 = WW2\Archives\WW2ArtAmbient
archive.05 = WW2\Archives\OFSPData
archive.06 = SEA_MAP\SEA_COH_Map_A01

[data:common:03]
folder = CoH\Engine\Data
archive.01 = Far_East_Mod\Archives\FEMOD_Engine
archive.02 = Engine\Archives\Engine 

[data:common:04]
folder = RelicOnline\Data
archive.01 = RelicOnline\Archives\RelicOnline

[data:sound_low]
folder = Far_East_Mod\DataSoundLow
archive.01 = Far_East_Mod\Archives\FEMOD_SoundLow
archive.02 = WW2\Archives\WW2SoundLow

[data:sound_high]
folder = Far_East_Mod\DataSoundHigh
archive.01 = Far_East_Mod\Archives\FEMOD_SoundHigh
archive.02 = WW2\Archives\WW2SoundHigh

[data:art_low]
folder = CoH\DataArtLow
archive.01 = WW2\Archives\WW2ArtLow

[data:art_high]
folder = CoH\DataArtHigh
archive.01 = WW2\Archives\WW2ArtHigh

[locale:English]
folder.01 = Far_East_Mod\Locale\English

[data:english:01]
folder = Far_East_Mod\Locale\English

[data:english:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechEnglish
archive.03 = WW2\Archives\WW2AlliesSpeechEnglish
archive.04 = WW2\Archives\WW2AxisSpeechEnglish
archive.05 = WW2\Archives\WW2SoundNISEnglish
archive.06 = WW2\Archives\OFCoreSpeechEnglish
archive.07 = WW2\Archives\OFFullSpeechEnglish

[data:english:03]
folder = Engine\Locale\English\Data
archive.01 = Engine\Archives\EngineEnglish

[locale:German]
folder.01 = Far_East_Mod\Locale\German

[data:german:01]
folder = Far_East_Mod\Locale\German

[data:german:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechGerman
archive.03 = WW2\Archives\WW2AlliesSpeechGerman
archive.04 = WW2\Archives\WW2AxisSpeechGerman
archive.05 = WW2\Archives\WW2SoundNISGerman
archive.06 = WW2\Archives\OFCoreSpeechGerman
archive.07 = WW2\Archives\OFFullSpeechGerman

[data:german:03]
folder = Engine\Locale\German\Data
archive.01 = Engine\Archives\EngineGerman

[locale:French]
folder.01 =Far_East_Mod\Locale\French

[data:french:01]
folder = Far_East_Mod\Locale\French

[data:french:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechFrench
archive.03 = WW2\Archives\WW2AlliesSpeechFrench
archive.04 = WW2\Archives\WW2AxisSpeechFrench
archive.05 = WW2\Archives\WW2SoundNISFrench
archive.06 = WW2\Archives\OFCoreSpeechFrench
archive.07 = WW2\Archives\OFFullSpeechFrench

[data:french:03]
folder = Engine\Locale\French\Data
archive.01 = Engine\Archives\EngineFrench

[locale:Spanish]
folder.01 =Far_East_Mod\Locale\Spanish

[data:spanish:01]
folder = Far_East_Mod\Locale\Spanish

[data:spanish:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechSpanish
archive.03 = WW2\Archives\WW2AlliesSpeechSpanish
archive.04 = WW2\Archives\WW2AxisSpeechSpanish
archive.05 = WW2\Archives\WW2SoundNISSpanish
archive.06 = WW2\Archives\OFCoreSpeechSpanish
archive.07 = WW2\Archives\OFFullSpeechSpanish

[data:spanish:03]
folder = Engine\Locale\Spanish\Data
archive.01 = Engine\Archives\EngineSpanish

[locale:Russian]
folder.01 = Far_East_Mod\Locale\Russian

[data:russian:01]
folder = Far_East_Mod\Locale\Russian

[data:russian:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechRussian
archive.03 = WW2\Archives\WW2AlliesSpeechRussian
archive.04 = WW2\Archives\WW2AxisSpeechRussian
archive.05 = WW2\Archives\WW2SoundNISRussian
archive.06 = WW2\Archives\OFCoreSpeechRussian
archive.07 = WW2\Archives\OFFullSpeechRussian

[data:russian:03]
folder = Engine\Locale\Russian\Data
archive.01 = Engine\Archives\EngineRussian

[locale:Italian]
folder.01 = Far_East_Mod\Locale\Italian

[data:italian:01]
folder = Far_East_Mod\Locale\Italian

[data:italian:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechEnglish
archive.03 = WW2\Archives\WW2AlliesSpeechEnglish
archive.04 = WW2\Archives\WW2AxisSpeechEnglish
archive.05 = WW2\Archives\WW2SoundNISEnglish
archive.06 = WW2\Archives\OFCoreSpeechEnglish
archive.07 = WW2\Archives\OFFullSpeechEnglish

[data:italian:03]
folder = CoH\Locale\Italian\Data
archive.01 = Engine\Archives\EngineItalian

[locale:Czech]
folder.01 = Far_East_Mod\Locale\Czech

[data:czech:01]
folder.01 = Far_East_Mod\Locale\Czech

[data:czech:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechEnglish
archive.03 = WW2\Archives\WW2AlliesSpeechEnglish
archive.04 = WW2\Archives\WW2AxisSpeechEnglish
archive.05 = WW2\Archives\WW2SoundNISEnglish
archive.06 = WW2\Archives\OFCoreSpeechEnglish
archive.07 = WW2\Archives\OFFullSpeechEnglish

[data:czech:03]
folder = Engine\Locale\Czech\Data
archive.01 = Engine\Archives\EngineCzech

[locale:Polish]
folder.01 = Far_East_Mod\Locale\Polish

[data:polish:01]
folder.01 = Far_East_Mod\Locale\Polish

[data:polish:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechEnglish
archive.03 = WW2\Archives\WW2AlliesSpeechEnglish
archive.04 = WW2\Archives\WW2AxisSpeechEnglish
archive.05 = WW2\Archives\WW2SoundNISEnglish
archive.06 = WW2\Archives\OFCoreSpeechEnglish
archive.07 = WW2\Archives\OFFullSpeechEnglish

[data:polish:03]
folder = Engine\Locale\Polish\Data
archive.01 = Engine\Archives\EnginePolish

[locale:ChineseTrad]
folder.01 = Far_East_Mod\Locale\ChineseTrad

[data:chinesetrad:01]
folder = CoH\Locale\ChineseTrad\Data

[data:chinesetrad:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechEnglish
archive.03 = WW2\Archives\WW2AlliesSpeechEnglish
archive.04 = WW2\Archives\WW2AxisSpeechEnglish
archive.05 = WW2\Archives\WW2SoundNISEnglish
archive.06 = WW2\Archives\OFCoreSpeechEnglish
archive.07 = WW2\Archives\OFFullSpeechEnglish

[data:chinesetrad:03]
folder = Engine\Locale\ChineseTrad\Data
archive.01 = Engine\Archives\EngineChineseTrad

[locale:Japanese]
folder.01 = Far_East_Mod\Locale\Japanese

[data:japanese:01]
folder.01 = Far_East_Mod\Locale\Japanese

[data:japanese:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechEnglish
archive.03 = WW2\Archives\WW2AlliesSpeechEnglish
archive.04 = WW2\Archives\WW2AxisSpeechEnglish
archive.05 = WW2\Archives\WW2SoundNISEnglish
archive.06 = WW2\Archives\OFCoreSpeechEnglish
archive.07 = WW2\Archives\OFFullSpeechEnglish

[data:japanese:03]
folder = Engine\Locale\Japanese\Data
archive.01 = Engine\Archives\EngineJapanese

[locale:korean]
folder.01 = Far_East_Mod\Locale\Korean

[data:korean:01]
folder.01 = Far_East_Mod\Locale\Korean

[data:korean:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechEnglish
archive.03 = WW2\Archives\WW2AlliesSpeechEnglish
archive.04 = WW2\Archives\WW2AxisSpeechEnglish
archive.05 = WW2\Archives\WW2SoundNISEnglish
archive.06 = WW2\Archives\OFCoreSpeechEnglish
archive.07 = WW2\Archives\OFFullSpeechEnglish

[data:korean:03]
folder = Engine\Locale\Korean\Data
archive.01 = Engine\Archives\EngineKorean

[locale:chineseenglish]
folder.01 = Far_East_Mod\Locale\ChineseEnglish

[data:chineseenglish:01]
folder = Far_East_Mod\Locale\ChineseEnglish
archive.01 = WW2\Archives\WW2Locale-ChineseEnglish

[data:chineseenglish:02]
folder = Far_East_Mod\DataSound
archive.01 = Far_East_Mod\Archives\FEMOD_SoundSpeech
archive.02 = WW2\Archives\WW2SoundSpeechEnglish
archive.03 = WW2\Archives\WW2AlliesSpeechEnglish
archive.04 = WW2\Archives\WW2AxisSpeechEnglish
archive.05 = WW2\Archives\WW2SoundNISEnglish
archive.06 = WW2\Archives\OFCoreSpeechEnglish
archive.07 = WW2\Archives\OFFullSpeechEnglish

[data:chineseenglish:03]
folder = Engine\Locale\ChineseEnglish\Data
archive.01 = Engine\Archives\ChineseEnglish

